Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true
Metrics/LineLength:
  IgnoredPatterns:
    - '^Given'
    - '^When'
    - '^Then'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: false

