language: ruby

sudo: required

dist: xenial

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7

env:
  - browser=chrome
  - browser=firefox

gemfile:
  - Gemfile

addons:
  chrome: stable
  firefox: latest

before_install:
  - gem install bundler -v 2.1.4

services:
  - xvfb

script:
  - bundle exec rake

branches:
  only:
    - master
